[project]
name = 'PDAS'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.analysis-marketplace]
path = 'contracts/analysis-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.biosignature-nft]
path = 'contracts/biosignature-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.sample-management]
path = 'contracts/sample-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
